const adventData = {
	day1: {
		src: "./../1.png",
		alt: "alt",
		id: "1",
		task: "Pójdźcie na zimowy spacer",
		imgTask: "./../walk.png",
	},
	day2: {
		src: "./src/assets/2.png",
		alt: "alt",
		id: "2",
		task: "Poszukajcie dekoracji świątecznych i przygotujcie dom na święta",
		imgTask: "./../decor.png",
	},
	day3: {
		src: "./../3.png",
		alt: "alt",
		id: "3",
		task: "Upieczcie Ciastka",
		imgTask: "./../ciastka.png",
	},
	day4: {
		src: "./../4.png",
		alt: "alt",
		id: "4",
		task: "Napiszcie List do Św. Mikołaja",
		imgTask: "./../letter.svg",
	},
	day5: {
		src: "./../5.png",
		alt: "alt",
		id: "5",
		task: "Przygotujcie poczęstunek dla Św. Mikołaja i Reniferów",
		imgTask: "./src/assets/treat.jpg",
	},
	day6: {
		src: "./src/assets/6.png",
		alt: "alt",
		id: "6",
		task: "Wypijcie Gorącą Czekoladę z przepisu Św.Mikołaja",
		imgTask: "./src/assets/chocolate.jpg",
	},
	day7: {
		src: "./src/assets/7.png",
		alt: "alt",
		id: "7",
		task: "Nauczcie się kolędy",
		imgTask: "./src/assets/carol.jpg",
	},
	day8: {
		src: "./src/assets/8.png",
		alt: "alt",
		id: "8",
		task: "Sprawdźcie Czy Ptaszki Mają Co Jeść",
		imgTask: "./src/assets/bird.jpg",
	},
	day9: {
		src: "./src/assets/9.png",
		alt: "alt",
		id: "9",
		task: "Przygotujcie kartki świąteczne",
		imgTask: "./src/assets/cards.jpg",
	},
	day10: {
		src: "./src/assets/10.png",
		alt: "alt",
		id: "10",
		task: "Pieczemy pierniczki",
		imgTask: "./src/assets/gingercookies.jpg",
	},
	day11: {
		src: "./src/assets/11.png",
		alt: "alt",
		id: "11",
		task: "Obejrzyjcie Świąteczną Bajkę ",
		imgTask: "./src/assets/tv.jpg",
	},
	day12: {
		src: "./src/assets/12.png",
		alt: "alt",
		id: "12",
		task: "Zatańczcie do Śwątecznych Piosenek",
		imgTask: "./src/assets/dance.jpg",
	},
	day13: {
		src: "./src/assets/13.png",
		alt: "alt",
		id: "13",
		task: "Dzień Relaksu",
		imgTask: "./src/assets/nap.jpg",
	},
	day14: {
		src: "./src/assets/14.png",
		alt: "alt",
		id: "14",
		task: "Czytamy Świąteczną Książkę",
		imgTask: "./src/assets/book.jpg",
	},
	day15: {
		src: "./src/assets/15.png",
		alt: "alt",
		id: "15",
		task: "Wymyślcie Dziś Sami Zadanie",
		imgTask: "./src/assets/idea.jpg",
	},
	day16: {
		src: "./src/assets/16.png",
		alt: "alt",
		id: "16",
		task: "Porozmawiajcie z Dziadkami jak Święta wyglądały, kiedy byli dziećmi",
		imgTask: "./src/assets/grand.jpg",
	},
	day17: {
		src: "./src/assets/17.png",
		alt: "alt",
		id: "17",
		task: "Zróbcie Domki z Piernika",
		imgTask: "./src/assets/house.jpg",
	},
	day18: {
		src: "./src/assets/18.png",
		alt: "alt",
		id: "18",
		task: "Wymyślcie Zadanie",
		imgTask: "./src/assets/idea.jpg",
	},
	day19: {
		src: "./src/assets/19.png",
		alt: "alt",
		id: "19",
		task: "Pieczemy ciastka",
		imgTask: "./src/assets/gingercookies.jpg",
	},
	day20: {
		src: "./src/assets/20.png",
		alt: "alt",
		id: "20",
		task: "Książka o Świętach",
		imgTask: "./src/assets/books.jpg",
	},
	day21: {
		src: "./src/assets/21.png",
		alt: "alt",
		id: "21",
		task: "Pograjcie w Grę ",
		imgTask: "./src/assets/game.jpg",
	},
	day22: {
		src: "./src/assets/22.png",
		alt: "alt",
		id: "22",
		task: "Porządki w Pokojach",
		imgTask: "./src/assets/clean.jpg",
	},
	day23: {
		src: "./src/assets/23.png",
		alt: "alt",
		id: "23",
		task: "Wielka Świąteczna Kąpiel",
		imgTask: "./src/assets/bath.jpg",
	},
	day24: {
		src: "./src/assets/24.png",
		alt: "alt",
		id: "24",
		task: "Ubierzcie się Elegancko",
		imgTask: "./src/assets/diner.jpg",
	},
}
export default adventData
