const adventData = {
	day1: {
		src: "./1.png",
		alt: "alt",
		id: "1",
		task: "Pójdźcie na zimowy spacer",
		imgTask: "./walk.png",
	},
	day2: {
		src: "./2.png",
		alt: "alt",
		id: "2",
		task: "Poszukajcie dekoracji świątecznych i przygotujcie dom na święta",
		imgTask: "./decor.png",
	},
	day3: {
		src: "./3.png",
		alt: "alt",
		id: "3",
		task: "Upieczcie Ciastka",
		imgTask: "./ciastka.png",
	},
	day4: {
		src: "./4.png",
		alt: "alt",
		id: "4",
		task: "Napiszcie List do Św. Mikołaja",
		imgTask: "./letter.svg",
	},
	day5: {
		src: "./5.png",
		alt: "alt",
		id: "5",
		task: "Przygotujcie poczęstunek dla Św. Mikołaja i Reniferów",
		imgTask: "./src/assets/treat.jpg",
	},
	day6: {
		src: "./6.png",
		alt: "alt",
		id: "6",
		task: "Wypijcie Gorącą Czekoladę z przepisu Św.Mikołaja",
		imgTask: "./chocolate.jpg",
	},
	day7: {
		src: "./7.png",
		alt: "alt",
		id: "7",
		task: "Nauczcie się kolędy",
		imgTask: ".//carol.jpg",
	},
	day8: {
		src: "./8.png",
		alt: "alt",
		id: "8",
		task: "Sprawdźcie Czy Ptaszki Mają Co Jeść",
		imgTask: "./bird.jpg",
	},
	day9: {
		src: "./9.png",
		alt: "alt",
		id: "9",
		task: "Przygotujcie kartki świąteczne",
		imgTask: "./cards.jpg",
	},
	day10: {
		src: "./10.png",
		alt: "alt",
		id: "10",
		task: "Pieczemy pierniczki",
		imgTask: "./gingercookies.jpg",
	},
	day11: {
		src: "./11.png",
		alt: "alt",
		id: "11",
		task: "Obejrzyjcie Świąteczną Bajkę ",
		imgTask: "./tv.jpg",
	},
	day12: {
		src: "./12.png",
		alt: "alt",
		id: "12",
		task: "Zatańczcie do Śwątecznych Piosenek",
		imgTask: "./dance.jpg",
	},
	day13: {
		src: "./13.png",
		alt: "alt",
		id: "13",
		task: "Dzień Relaksu",
		imgTask: "./nap.jpg",
	},
	day14: {
		src: "./14.png",
		alt: "alt",
		id: "14",
		task: "Czytamy Świąteczną Książkę",
		imgTask: "./book.jpg",
	},
	day15: {
		src: "./15.png",
		alt: "alt",
		id: "15",
		task: "Wymyślcie Dziś Sami Zadanie",
		imgTask: "./idea.jpg",
	},
	day16: {
		src: "./16.png",
		alt: "alt",
		id: "16",
		task: "Porozmawiajcie z Dziadkami jak Święta wyglądały, kiedy byli dziećmi",
		imgTask: "./grand.jpg",
	},
	day17: {
		src: "./17.png",
		alt: "alt",
		id: "17",
		task: "Zróbcie Domki z Piernika",
		imgTask: "./house.jpg",
	},
	day18: {
		src: "./18.png",
		alt: "alt",
		id: "18",
		task: "Wymyślcie Zadanie",
		imgTask: "./idea.jpg",
	},
	day19: {
		src: "./19.png",
		alt: "alt",
		id: "19",
		task: "Pieczemy ciastka",
		imgTask: "./gingercookies.jpg",
	},
	day20: {
		src: "./20.png",
		alt: "alt",
		id: "20",
		task: "Książka o Świętach",
		imgTask: "./books.jpg",
	},
	day21: {
		src: "./21.png",
		alt: "alt",
		id: "21",
		task: "Pograjcie w Grę ",
		imgTask: "./game.jpg",
	},
	day22: {
		src: "./22.png",
		alt: "alt",
		id: "22",
		task: "Porządki w Pokojach",
		imgTask: "./clean.jpg",
	},
	day23: {
		src: "./23.png",
		alt: "alt",
		id: "23",
		task: "Wielka Świąteczna Kąpiel",
		imgTask: "./bath.jpg",
	},
	day24: {
		src: "./24.png",
		alt: "alt",
		id: "24",
		task: "Ubierzcie się Elegancko",
		imgTask: "./diner.jpg",
	},
}
export default adventData
