const adventData = {
	day1: {
		src: "./src/assets/1.png",
		alt: "alt",
		id: "?",
	},
	day2: { src: "./src/assets/2.png", alt: "alt", id: "?" },
	day3: { src: "./src/assets/3.png", alt: "alt", id: "?" },
	day4: { src: "./src/assets/4.png", alt: "alt", id: "?" },
	day5: { src: "./src/assets/5.png", alt: "alt", id: "?" },
	day6: { src: "./src/assets/6.png", alt: "alt", id: "?" },
	day7: { src: "./src/assets/7.png", alt: "alt", id: "?" },
	day8: { src: "./src/assets/8.png", alt: "alt", id: "?" },
	day9: { src: "./src/assets/9.png", alt: "alt", id: "?" },
	day10: { src: "./src/assets/10.png", alt: "alt", id: "?" },
	day11: { src: "./src/assets/11.png", alt: "alt", id: "?" },
	day12: { src: "./src/assets/12.png", alt: "alt", id: "?" },
	day13: { src: "./src/assets/13.png", alt: "alt", id: "?" },
	day14: { src: "./src/assets/14.png", alt: "alt", id: "?" },
	day15: { src: "./src/assets/15.png", alt: "alt", id: "?" },
	day16: { src: "./src/assets/16.png", alt: "alt", id: "?" },
	day17: { src: "./src/assets/17.png", alt: "alt", id: "?" },
	day18: { src: "./src/assets/18.png", alt: "alt", id: "?" },
	day19: { src: "./src/assets/19.png", alt: "alt", id: "?" },
	day20: { src: "./src/assets/20.png", alt: "alt", id: "?" },
	day21: { src: "./src/assets/21.png", alt: "alt", id: "?" },
	day22: { src: "./src/assets/22.png", alt: "alt", id: "?" },
	day23: { src: "./src/assets/23.png", alt: "alt", id: "?" },
	day24: { src: "./src/assets/24.png", alt: "alt", id: "?" },
}
export default adventData
